services:
  - type: web
    name: petr-archives-api
    env: python
    repo: https://github.com/datbeo2001/petr-archives-backend
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.5
      - key: CLOUDINARY_URL
        sync: false
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn --workers 4 main:app --host 0.0.0.0 --port 10000"
